# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/appodeal/CocoaPods.git'

target 'appodeal_ios_demo_swift_app' do
    pod 'Appodeal', '1.3.3' # for XCODE 8
end
